---
version: 2.1

orbs:
  python: circleci/python@2.1.1

executors:
  python:
    docker:
      - image: circleci/python:3.7

aliases:
  # TODO activate CI only on master for now
  all_branches_and_tags: &all_branches_and_tags
    filters:
      tags:
        only: /.*/
      branches:
        only: /.*/

jobs:
  cythonize:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --deploy
      - run:
          command: |
            ./setup.py build_ext -i -j2
      - persist_to_workspace:
          paths:
            - build
            - cyperf
          root: .
  lint:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --deploy --dev
      - run:
          command: |
            pipenv run pylint labeledmatrix cyperf
          name: pylint
  tests:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --deploy --dev
      - run:
          command: |
            pipenv run pytest tests --durations=10
          name: unit-tests
  build:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --deploy
      - run:
          command: |
            python setup.py build_ext -i -j2 bdist_wheel
            pip install twine
            twine upload dist/*
          name: build
      - persist_to_workspace:
          paths:
            - dist
          root: .

workflows:
  build:
    jobs:
      - cythonize:
          name: cython_setup_dev
          <<: *all_branches_and_tags
      - lint:
          name: lint
          requires:
            - cython_setup_dev
          <<: *all_branches_and_tags
      - tests:
          name: unit_tests
          requires:
            - cython_setup_dev
          <<: *all_branches_and_tags
      - build:  # running inside pipenv because of complex dependencies in setup.py
          name: deploy_wheel
          context: artifactory
          <<: *all_branches_and_tags
