FROM python:3.7-buster as requirements
RUN pip install --upgrade pip
RUN pip install pipenv
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock
COPY setup.py setup.py
RUN pipenv requirements --dev > /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt --no-deps
RUN python setup.py build_ext --inplace

COPY . /src
WORKDIR /src
